name    'puppet-openstack-ha'
version '1.0.0'
source  'https://github.com/CiscoSystems/puppet-openstack-ha'
author  'Daneyon Hansen'
license 'Apache License 2.0'
summary 'Openstack Puppet Module for Folsom High-Availablity'
description 'Module to install openstack-folsom HA configurations using puppet'
project_page 'https://github.com/CiscoSystems/puppet-openstack-ha'

dependency 'puppet/apache'
dependency 'puppet/apt'
dependency 'puppet/apt-cahcer-ng'
dependency 'puppet/augeas'
dependency 'puppet/boolean'
dependency 'puppet/cinder'
dependency 'puppet/cobbler'
dependency 'puppet/concat'
dependency 'puppet/create_resources'
dependency 'puppet/dnsmasq'
dependency 'puppet/filemapper'
dependency 'puppet/glance'
dependency 'puppet/haproxy'
dependency 'puppet/horizon'
dependency 'puppet/inifile'
dependency 'puppet/keepalived'
dependency 'puppet/keystone'
dependency 'puppet/lvm'
dependency 'puppet/memcached'
dependency 'puppet/mysql'
dependency 'puppet/network'
dependency 'puppet/nova'
dependency 'puppet/ntp'
dependency 'puppet/openstack'
dependency 'puppet/pip'
dependency 'puppet/puppet'
dependency 'puppet/neutron'
dependency 'puppet/rabbitmq'
dependency 'puppet/rsync'
dependency 'puppet/ssh'
dependency 'puppet/stdlib'
dependency 'puppet/swift'
dependency 'puppet/sysctl'
dependency 'puppet/vswitch'
dependency 'puppet/xinetd' 
